
development:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-25-numbers_development
  pool: 5
  host: localhost
  username: nickyhughes
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-25-numbers_test
  pool: 5
  host: localhost
  username: nickyhughes
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: r2013-03-25-numbers_production
  pool: 5
  host: localhost
  username: nickyhughes
  password:
